CREATE TABLE targets (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    uri TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE healthchecks (
    id UUID PRIMARY KEY,
    target_id UUID NOT NULL REFERENCES targets(id),
    status TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
)