name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Configure AWS Credentials
      run: | 
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export AWS_REGION="eu-west-1"
        
    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init
      
    - name: Build
      working-directory: ./src
      run: go build -v ./...
      
    - name: Test
      working-directory: ./src
      run: go test -v ./...

    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -no-color

    - name: Terraform Apply
      working-directory: ./infrastructure
      run: terraform apply -auto-approve
