name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-1"
        
    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init
      
    - name: Build
      working-directory: ./src
      run: go build -v ./...
      
    - name: Test
      working-directory: ./src
      run: go test -v ./...

    - name: Docker Build
      working-directory: ./src
      env:
        ACCOUNT: ${{ secrets.AWS_ACCESS_KEY_ID }}
        REGION: "eu-west-1"
        REPO: "healthcheck-be"
      run: |
        docker build -t $ACCOUNT.dkr.ecr.eu-west-1.amazonaws.com/healthcheck-be:latest .
        aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
        docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO

    - name: Terraform Plan
      env:
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_AWS_REGION: "eu-west-1"
        TF_VAR_RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        TF_VAR_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      working-directory: ./infrastructure
      run: terraform plan -no-color

    - name: Terraform Apply
      env:
        TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_AWS_REGION: "eu-west-1"
        TF_VAR_RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        TF_VAR_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      working-directory: ./infrastructure
      run: terraform apply -auto-approve
